# Create a new spin result
POST https://notion-api-rust.onrender.com/spin-results
Content-Type: application/json

{
    "key": "123123",
    "datetime": "2025-03-06T00:00:00Z",
    "number": 100,
    "is_win": true,
    "checked": false
}

### Get all spin results
GET http://localhost:3000/spin-results

### Get root
GET http://localhost:3000/

### Update a spin result
PUT http://localhost:3000/spin-results/your-page-id-here
Content-Type: application/json

{
    "key": "1234567890",
    "datetime": "2025-03-06T00:00:00Z",
    "number": 200,
    "is_win": true,
    "checked": true
}

### Delete a spin result
DELETE http://localhost:3000/spin-results/your-page-id-here
